### ISSUE TITLE
Google maps not working

### ISSUE THREAD

**Issue by letiesperon** [forsaken1/activeadmin-latlng#12]
Hi! Cool gem. 
I'm having some issues though. 

If I add 

`f.latlng lang: :en, map: :google, id_lat: :user_latitude, id_lng: :user_longitude`

It does not work :( Do you know what's going on?

**Comment by forsaken1** [comment]
@letiesperon Hello! Thanks! Try `f.latlng`, I think `id_lat` and `id_lng` inputs not found on your admin page

**Comment by letiesperon** [comment]
I updated and it works. I wasn't including the google api key and I didn't have my key allowed for the needed services: Google maps js API, and places autocomplete right? 

I'm closing this since it was my fault.
