### ISSUE TITLE
MissingKeyMapError

### ISSUE THREAD

**Issue by salihsagdilek** [forsaken1/activeadmin-latlng#3]
<img width="1648" alt="screen shot 2017-09-16 at 12 38 46" src="https://user-images.githubusercontent.com/9050352/30511176-4308cb38-9adc-11e7-8760-01b430bbe7fe.png">

[https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error](url)

i didnt see where to enter

**Comment by forsaken1** [comment]
https://github.com/forsaken1/activeadmin-latlng/pull/4 Hello, @salihsagdilek! I add new feature - now you can send _api key_ directly (unsafe) or send **name of ENV-variable** where storing _api key_.
