### ISSUE TITLE
How to display map in SHOW view?

### ISSUE THREAD

**Issue by frobert** [forsaken1/activeadmin-latlng#34]
How to display map in SHOW or INDEX view?

Thanks.

**Comment by babarajay** [comment]
Hello @frobert,

Did you get any solution?

**Comment by frobert** [comment]
> Hello @frobert,
> 
> Did you get any solution?

Hey, it is a while, so I'm not sure if I found an optimal solution and just created a link to new winfow to display the map...

best regards
